title: Awesome Buttons Showcase
description: A collection of visually striking and interactive buttons
baseurl: "/BUTTONS"
url: "https://tmhsdigital.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _includes

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/